-- MySQL Script generated by MySQL Workbench
-- dom 07 abr 2019 10:46:44 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema model_bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema model_bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `model_bank` DEFAULT CHARACTER SET utf8 ;
USE `model_bank` ;

-- -----------------------------------------------------
-- Table `model_bank`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model_bank`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `password` CHAR(32) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model_bank`.`avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model_bank`.`avatar` (
  `avatar_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `life` INT NOT NULL,
  `life_max` INT NOT NULL,
  `xp` INT NOT NULL,
  `xp_max` INT NOT NULL,
  `level` INT NOT NULL,
  PRIMARY KEY (`avatar_id`),
  INDEX `foreing_key_idx` (`user_id` ASC),
  CONSTRAINT `foreing_key`
    FOREIGN KEY (`user_id`)
    REFERENCES `model_bank`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model_bank`.`opponent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model_bank`.`opponent` (
  `opponent_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `life` INT NOT NULL,
  `life_max` INT NOT NULL,
  `xp` INT NOT NULL,
  PRIMARY KEY (`opponent_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
